### ISSUE TITLE
Handling style

### ISSUE THREAD

**Issue by marcfedorow** [Kaban4/lab#52]
https://github.com/Kaban4/lab/blob/b36e768336c24654c52e9a0dacdf2582e32b8f74/Source.ipp#L13
[Why you should catch by reference](https://ptgmedia.pearsoncmg.com/images/0321113586/items/sutter_item73.pdf) and [why this reference should be const](https://stackoverflow.com/questions/2522299/c-catch-blocks-catch-exception-by-value-or-reference).
Issue #45 comment contains the correct code. You should have just copied the code.

**Comment by Kaban4** [comment]
I'm trying to write myself, don't use copy-paste(

**Comment by marcfedorow** [comment]
You just try to invent the bicycle tho ¯\_(ツ)_/¯
